# Change these first
owner: codeminer-co # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ghoomo Phiroo API
    url: https://api.ghoomophiroo.com/status
  - name: Prophecy API
    url: https://prophecy.codeminer.co:3004/status
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.codeminer.co
  # baseUrl: /your-repo-name
  logoUrl: https://codeminer.co/wp-content/uploads/2020/09/Asset-4.png
  name: CodeMiners UpTime Monitor
  introTitle: "CodeMiners Uptime Tracker – Your Reliable Monitoring Solution"
  introMessage: "Welcome to the CodeMiners Uptime Tracker, a comprehensive monitoring system ensuring the reliability and performance of our services. Powered by GitHub Actions, our tracker provides real-time updates on system status and downtime — no additional server required. Stay informed with actionable insights and transparent reporting. Built and maintained by the experts at CodeMiners, we guarantee a seamless experience for your business operations."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
